# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "asset_hat"
  s.version = "0.4.2.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ron DeVera", "Mint Digital"]
  s.date = "2012-04-17"
  s.description = "Load CSS and JS faster. Minifies, bundles, and optimizes CSS/JS assets ahead of time (e.g., on deploy), not at runtime. Loads popular third-party JS (like jQuery, YUI, and Dojo) from localhost in development, and auto-switches to Google's CDN in production. Lets you switch on LABjs mode to load more scripts in parallel. Can rewrite stylesheets to use CDN hosts (not just your web server) and cache-busting hashes for updated images."
  s.email = "hello@rondevera.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "HISTORY",
    "LICENSE",
    "README.rdoc",
    "RELEASE",
    "Rakefile",
    "VERSION.yml",
    "asset_hat.gemspec",
    "config/assets.yml",
    "doc/classes/AssetHat.html",
    "doc/classes/AssetHat/CSS.html",
    "doc/classes/AssetHat/CSS/Engines.html",
    "doc/classes/AssetHat/Fingerprint.html",
    "doc/classes/AssetHat/JS.html",
    "doc/classes/AssetHat/JS/Engines.html",
    "doc/classes/AssetHatHelper.html",
    "doc/created.rid",
    "doc/files/HISTORY.html",
    "doc/files/LICENSE.html",
    "doc/files/README_rdoc.html",
    "doc/files/lib/asset_hat/capistrano_rb.html",
    "doc/files/lib/asset_hat/css_rb.html",
    "doc/files/lib/asset_hat/fingerprint_rb.html",
    "doc/files/lib/asset_hat/initializers/action_view_rb.html",
    "doc/files/lib/asset_hat/initializers/cache_fingerprints_rb.html",
    "doc/files/lib/asset_hat/js_rb.html",
    "doc/files/lib/asset_hat/railtie_rb.html",
    "doc/files/lib/asset_hat/tasks/css_rb.html",
    "doc/files/lib/asset_hat/tasks/js_rb.html",
    "doc/files/lib/asset_hat/tasks_rb.html",
    "doc/files/lib/asset_hat/unicorn_rb.html",
    "doc/files/lib/asset_hat/version_rb.html",
    "doc/files/lib/asset_hat_helper_rb.html",
    "doc/files/lib/asset_hat_rb.html",
    "doc/files/lib/tasks/asset_hat_rake.html",
    "doc/fr_class_index.html",
    "doc/fr_file_index.html",
    "doc/fr_method_index.html",
    "doc/index.html",
    "doc/rdoc-style.css",
    "lib/asset_hat.rb",
    "lib/asset_hat/capistrano.rb",
    "lib/asset_hat/css.rb",
    "lib/asset_hat/fingerprint.rb",
    "lib/asset_hat/initializers/action_view.rb",
    "lib/asset_hat/initializers/cache_fingerprints.rb",
    "lib/asset_hat/js.rb",
    "lib/asset_hat/railtie.rb",
    "lib/asset_hat/tasks.rb",
    "lib/asset_hat/tasks/css.rb",
    "lib/asset_hat/tasks/js.rb",
    "lib/asset_hat/unicorn.rb",
    "lib/asset_hat/version.rb",
    "lib/asset_hat_helper.rb",
    "lib/tasks/asset_hat.rake",
    "public/javascripts/bundles/js-bundle-1.min.111.js",
    "public/javascripts/bundles/js-bundle-2.min.111.js",
    "public/javascripts/js-file-1-1.js",
    "public/javascripts/js-file-1-2.js",
    "public/javascripts/js-file-1-3.js",
    "public/javascripts/js-file-2-1.js",
    "public/javascripts/js-file-2-2.js",
    "public/javascripts/js-file-2-3.js",
    "public/stylesheets/bundles/css-bundle-1.min.css",
    "public/stylesheets/bundles/css-bundle-2.min.css",
    "public/stylesheets/bundles/ssl/css-bundle-1.min.css",
    "public/stylesheets/bundles/ssl/css-bundle-2.min.css",
    "public/stylesheets/bundles/ssl/css-bundle-3.min.css",
    "public/stylesheets/css-file-1-1.css",
    "public/stylesheets/css-file-1-2.css",
    "public/stylesheets/css-file-1-3.css",
    "public/stylesheets/css-file-2-1.css",
    "public/stylesheets/css-file-2-2.css",
    "public/stylesheets/css-file-2-3.css",
    "rails/init.rb",
    "script/preview_github_readme",
    "test/asset_hat_fingerprint_test.rb",
    "test/asset_hat_helper_test.rb",
    "test/asset_hat_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://mintdigital.github.com/asset_hat"
  s.require_paths = ["lib"]
  s.summary = "Your assets are covered."

  s.add_development_dependency(%q<actionpack>, ["~> 3.0.0"])
  s.add_development_dependency(%q<flexmock>, ["~> 0.8.6"])
  s.add_development_dependency(%q<hanna>, ["~> 0.1.12"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
  s.add_development_dependency(%q<shoulda>, ["~> 2.10.2"])
  s.add_development_dependency(%q<simplecov>, ["~> 0.6.1"])
  s.add_development_dependency(%q<test-unit>, ["~> 2.0.0"])
  s.add_runtime_dependency(%q<cssmin>, ["~> 1.0.2"])
  s.add_runtime_dependency(%q<jsmin>, ["~> 1.0.1"])
end

